/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.educativesoftware.view;

import java.awt.CardLayout;

/**
 *
 * @author Daniel Codena, CodeBreakers, @ESPE
 */
public class FrmAdminDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAdminDashboard.class.getName());

    private CardLayout cardLayout;
    private PnlCourseManagement pnlCourseManagement;

    /**
     * Creates new form IScreen
     */
    public FrmAdminDashboard() {
        initComponents();

        cardLayout = (CardLayout) mainPanel.getLayout();

        pnlCourseManagement = new PnlCourseManagement();

        mainPanel.add(new PnlDashboard(), "dashboard");
        mainPanel.add(new PnlStudents(), "students");
        mainPanel.add(new PnlCourses(), "courses");
        mainPanel.add(new PnlAlerts(), "alerts");
        mainPanel.add(new PnlHelp(), "help");
        mainPanel.add(new PnlTeachers(), "teachers");
        mainPanel.add(new PnlClassification(), "classification");
        mainPanel.add(new PnlCourseManagement(), "courseManagement");

        mainPanel.add(pnlCourseManagement, "courseManagement");

        cardLayout.show(mainPanel, "dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miLogIn = new javax.swing.JMenuItem();
        miLogOut = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenu();
        menuStudents = new javax.swing.JMenu();
        miRegisterStudent = new javax.swing.JMenuItem();
        miConsultStudent = new javax.swing.JMenuItem();
        miEditStudent = new javax.swing.JMenuItem();
        miDeleteStudent = new javax.swing.JMenuItem();
        menuTeachers = new javax.swing.JMenu();
        miRegisterTeacher = new javax.swing.JMenuItem();
        miConsultTeacher = new javax.swing.JMenuItem();
        miEditTeacher = new javax.swing.JMenuItem();
        miDeleteTeacher = new javax.swing.JMenuItem();
        menuClassification = new javax.swing.JMenu();
        miPerformance = new javax.swing.JMenuItem();
        miTypeOfLearning = new javax.swing.JMenuItem();
        miLearningPace = new javax.swing.JMenuItem();
        menuCourse = new javax.swing.JMenu();
        menuCourseManagment = new javax.swing.JMenu();
        miCreateCourse = new javax.swing.JMenuItem();
        miConsultCourse = new javax.swing.JMenuItem();
        miEditCourse = new javax.swing.JMenuItem();
        miDeleteCourse = new javax.swing.JMenuItem();
        menuOpenCourse = new javax.swing.JMenu();
        miIngles = new javax.swing.JMenuItem();
        menuAlerts = new javax.swing.JMenu();
        miLowPerformance = new javax.swing.JMenuItem();
        miLowParticipation = new javax.swing.JMenuItem();
        miHistory = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        miManual = new javax.swing.JMenuItem();
        miAbout = new javax.swing.JMenuItem();
        miCredits = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Educational App");
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setSize(new java.awt.Dimension(1200, 700));

        mainPanel.setLayout(new java.awt.CardLayout());

        menuFile.setText("Archivo");

        miLogIn.setText("Iniciar sesión");
        menuFile.add(miLogIn);

        miLogOut.setText("Cerrar sesión");
        menuFile.add(miLogOut);

        miExit.setText("Salir");
        menuFile.add(miExit);

        jMenuBar1.add(menuFile);

        menuUser.setText("Usuarios");

        menuStudents.setText("Estudiantes");

        miRegisterStudent.setText("Registrar");
        miRegisterStudent.addActionListener(this::miRegisterStudentActionPerformed);
        menuStudents.add(miRegisterStudent);

        miConsultStudent.setText("Consultar");
        miConsultStudent.addActionListener(this::miConsultStudentActionPerformed);
        menuStudents.add(miConsultStudent);

        miEditStudent.setText("Editar");
        miEditStudent.addActionListener(this::miEditStudentActionPerformed);
        menuStudents.add(miEditStudent);

        miDeleteStudent.setText("Eliminar");
        miDeleteStudent.addActionListener(this::miDeleteStudentActionPerformed);
        menuStudents.add(miDeleteStudent);

        menuUser.add(menuStudents);

        menuTeachers.setText("Docentes");

        miRegisterTeacher.setText("Registrar");
        miRegisterTeacher.addActionListener(this::miRegisterTeacherActionPerformed);
        menuTeachers.add(miRegisterTeacher);

        miConsultTeacher.setText("Consultar");
        miConsultTeacher.addActionListener(this::miConsultTeacherActionPerformed);
        menuTeachers.add(miConsultTeacher);

        miEditTeacher.setText("Editar");
        miEditTeacher.addActionListener(this::miEditTeacherActionPerformed);
        menuTeachers.add(miEditTeacher);

        miDeleteTeacher.setText("Eliminar");
        miDeleteTeacher.addActionListener(this::miDeleteTeacherActionPerformed);
        menuTeachers.add(miDeleteTeacher);

        menuUser.add(menuTeachers);

        menuClassification.setText("Clasificación");

        miPerformance.setText("Rendimiento");
        miPerformance.addActionListener(this::miPerformanceActionPerformed);
        menuClassification.add(miPerformance);

        miTypeOfLearning.setText("Tipo de aprendizaje");
        miTypeOfLearning.addActionListener(this::miTypeOfLearningActionPerformed);
        menuClassification.add(miTypeOfLearning);

        miLearningPace.setText("Ritmo de aprendizaje");
        miLearningPace.addActionListener(this::miLearningPaceActionPerformed);
        menuClassification.add(miLearningPace);

        menuUser.add(menuClassification);

        jMenuBar1.add(menuUser);

        menuCourse.setText("Cursos");

        menuCourseManagment.setText("Gestionar Cursos");

        miCreateCourse.setText("Crear Cursos");
        miCreateCourse.addActionListener(this::miCreateCourseActionPerformed);
        menuCourseManagment.add(miCreateCourse);

        miConsultCourse.setText("Consultar Cursos");
        miConsultCourse.addActionListener(this::miConsultCourseActionPerformed);
        menuCourseManagment.add(miConsultCourse);

        miEditCourse.setText("Editar Curso");
        miEditCourse.addActionListener(this::miEditCourseActionPerformed);
        menuCourseManagment.add(miEditCourse);

        miDeleteCourse.setText("Eliminar Curso");
        miDeleteCourse.addActionListener(this::miDeleteCourseActionPerformed);
        menuCourseManagment.add(miDeleteCourse);

        menuCourse.add(menuCourseManagment);

        menuOpenCourse.setText("Abrir Cursos");

        miIngles.setText("Inglés");
        miIngles.addActionListener(this::miInglesActionPerformed);
        menuOpenCourse.add(miIngles);

        menuCourse.add(menuOpenCourse);

        jMenuBar1.add(menuCourse);

        menuAlerts.setText("Alertas");

        miLowPerformance.setText("Bajo Rendimiento");
        miLowPerformance.addActionListener(this::miLowPerformanceActionPerformed);
        menuAlerts.add(miLowPerformance);

        miLowParticipation.setText("Baja Participación");
        miLowParticipation.addActionListener(this::miLowParticipationActionPerformed);
        menuAlerts.add(miLowParticipation);

        miHistory.setText("Historial");
        miHistory.addActionListener(this::miHistoryActionPerformed);
        menuAlerts.add(miHistory);

        jMenuBar1.add(menuAlerts);

        menuHelp.setText("Ayuda");

        miManual.setText("Manual");
        miManual.addActionListener(this::miManualActionPerformed);
        menuHelp.add(miManual);

        miAbout.setText("Acerca de");
        miAbout.addActionListener(this::miAboutActionPerformed);
        menuHelp.add(miAbout);

        miCredits.setText("Créditos");
        miCredits.addActionListener(this::miCreditsActionPerformed);
        menuHelp.add(miCredits);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miConsultCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultCourseActionPerformed
        pnlCourseManagement.showTab(1);
        cardLayout.show(mainPanel, "courseManagement");

    }//GEN-LAST:event_miConsultCourseActionPerformed

    private void miRegisterStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegisterStudentActionPerformed
        cardLayout.show(mainPanel, "students");
    }//GEN-LAST:event_miRegisterStudentActionPerformed

    private void miConsultStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultStudentActionPerformed
        cardLayout.show(mainPanel, "students");
    }//GEN-LAST:event_miConsultStudentActionPerformed

    private void miEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditStudentActionPerformed
        cardLayout.show(mainPanel, "students");
    }//GEN-LAST:event_miEditStudentActionPerformed

    private void miDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteStudentActionPerformed
        cardLayout.show(mainPanel, "students");
    }//GEN-LAST:event_miDeleteStudentActionPerformed

    private void miRegisterTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegisterTeacherActionPerformed
        cardLayout.show(mainPanel, "teachers");
    }//GEN-LAST:event_miRegisterTeacherActionPerformed

    private void miConsultTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultTeacherActionPerformed
        cardLayout.show(mainPanel, "teachers");
    }//GEN-LAST:event_miConsultTeacherActionPerformed

    private void miEditTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditTeacherActionPerformed
        cardLayout.show(mainPanel, "teachers");
    }//GEN-LAST:event_miEditTeacherActionPerformed

    private void miDeleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteTeacherActionPerformed
        cardLayout.show(mainPanel, "teachers");
    }//GEN-LAST:event_miDeleteTeacherActionPerformed

    private void miInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInglesActionPerformed
        cardLayout.show(mainPanel, "courses");
    }//GEN-LAST:event_miInglesActionPerformed

    private void miPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPerformanceActionPerformed
        cardLayout.show(mainPanel, "classification");
    }//GEN-LAST:event_miPerformanceActionPerformed

    private void miTypeOfLearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTypeOfLearningActionPerformed
        cardLayout.show(mainPanel, "classification");
    }//GEN-LAST:event_miTypeOfLearningActionPerformed

    private void miLearningPaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLearningPaceActionPerformed
        cardLayout.show(mainPanel, "classification");
    }//GEN-LAST:event_miLearningPaceActionPerformed

    private void miCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreateCourseActionPerformed
        pnlCourseManagement.showTab(0);
        cardLayout.show(mainPanel, "courseManagement");

    }//GEN-LAST:event_miCreateCourseActionPerformed

    private void miEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditCourseActionPerformed
        pnlCourseManagement.showTab(2);
        cardLayout.show(mainPanel, "courseManagement");
    }//GEN-LAST:event_miEditCourseActionPerformed

    private void miDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteCourseActionPerformed
        pnlCourseManagement.showTab(3);
        cardLayout.show(mainPanel, "courseManagement");
    }//GEN-LAST:event_miDeleteCourseActionPerformed

    private void miLowPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLowPerformanceActionPerformed
        cardLayout.show(mainPanel, "alerts");
    }//GEN-LAST:event_miLowPerformanceActionPerformed

    private void miLowParticipationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLowParticipationActionPerformed
        cardLayout.show(mainPanel, "alerts");
    }//GEN-LAST:event_miLowParticipationActionPerformed

    private void miHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHistoryActionPerformed
        cardLayout.show(mainPanel, "alerts");
    }//GEN-LAST:event_miHistoryActionPerformed

    private void miManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManualActionPerformed
        cardLayout.show(mainPanel, "help");
    }//GEN-LAST:event_miManualActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        cardLayout.show(mainPanel, "help");
    }//GEN-LAST:event_miAboutActionPerformed

    private void miCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreditsActionPerformed
        cardLayout.show(mainPanel, "help");
    }//GEN-LAST:event_miCreditsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menuAlerts;
    private javax.swing.JMenu menuClassification;
    private javax.swing.JMenu menuCourse;
    private javax.swing.JMenu menuCourseManagment;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuOpenCourse;
    private javax.swing.JMenu menuStudents;
    private javax.swing.JMenu menuTeachers;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miConsultCourse;
    private javax.swing.JMenuItem miConsultStudent;
    private javax.swing.JMenuItem miConsultTeacher;
    private javax.swing.JMenuItem miCreateCourse;
    private javax.swing.JMenuItem miCredits;
    private javax.swing.JMenuItem miDeleteCourse;
    private javax.swing.JMenuItem miDeleteStudent;
    private javax.swing.JMenuItem miDeleteTeacher;
    private javax.swing.JMenuItem miEditCourse;
    private javax.swing.JMenuItem miEditStudent;
    private javax.swing.JMenuItem miEditTeacher;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miHistory;
    private javax.swing.JMenuItem miIngles;
    private javax.swing.JMenuItem miLearningPace;
    private javax.swing.JMenuItem miLogIn;
    private javax.swing.JMenuItem miLogOut;
    private javax.swing.JMenuItem miLowParticipation;
    private javax.swing.JMenuItem miLowPerformance;
    private javax.swing.JMenuItem miManual;
    private javax.swing.JMenuItem miPerformance;
    private javax.swing.JMenuItem miRegisterStudent;
    private javax.swing.JMenuItem miRegisterTeacher;
    private javax.swing.JMenuItem miTypeOfLearning;
    // End of variables declaration//GEN-END:variables
}
